services:
    db:
        image: mysql/mysql-server:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: '1'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'xhamster'
            MYSQL_USER: 'xhamster'
            MYSQL_PASSWORD: '1'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './schema.sql:/docker-entrypoint-initdb.d/10-schema.sql'
